### ISSUE TITLE
Any screenshot?

### ISSUE THREAD

**Issue by eneim** [CROSP/pretty-toast#1]
Thanks for the library. I'm curious how the Toast looks like now :D.

**Comment by CROSP** [comment]
Hi, thank you for response, you can make it look as you like) You can use custom views, or predefined toasts. 
I am going to add screenshots soon.
Thank you.

**Comment by anvesh523** [comment]
:+1:

**Comment by crysan** [comment]
+

**Comment by CROSP** [comment]
I have added screenshot, please have a look.

Also I have created script for taking screenshots and screencasts from android screen and convert it in GIF file. Have a look https://github.com/CROSP/android-screen2gif

**Comment by crysan** [comment]
Ty!
